// Code generated by mockery v1.0.0
package aggregatemock

import (
	core "github.com/yandex/pandora/core"
	mock "github.com/stretchr/testify/mock"
)

// SampleEncoder is an autogenerated mock type for the SampleEncoder type
type SampleEncoder struct {
	mock.Mock
}

// Encode provides a mock function with given fields: s
func (_m *SampleEncoder) Encode(s core.Sample) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(core.Sample) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Flush provides a mock function with given fields:
func (_m *SampleEncoder) Flush() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
