package ammomocks

import "github.com/yandex/pandora/aggregate"
import "github.com/yandex/pandora/ammo"
import "net/http"
import "github.com/stretchr/testify/mock"

// HTTP is an autogenerated mock type for the HTTP type
type HTTP struct {
	mock.Mock
}

// Request provides a mock function with given fields:
func (_m *HTTP) Request() (*http.Request, *aggregate.Sample) {
	ret := _m.Called()

	var r0 *http.Request
	if rf, ok := ret.Get(0).(func() *http.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	var r1 *aggregate.Sample
	if rf, ok := ret.Get(1).(func() *aggregate.Sample); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*aggregate.Sample)
		}
	}

	return r0, r1
}

var _ ammo.HTTP = (*HTTP)(nil)
