// Code generated by mockery v2.20.2. DO NOT EDIT.

package iomock

import mock "github.com/stretchr/testify/mock"

// WriteCloser is an autogenerated mock type for the WriteCloser type
type WriteCloser struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *WriteCloser) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: p
func (_m *WriteCloser) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWriteCloser interface {
	mock.TestingT
	Cleanup(func())
}

// NewWriteCloser creates a new instance of WriteCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWriteCloser(t mockConstructorTestingTNewWriteCloser) *WriteCloser {
	mock := &WriteCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
