// Code generated by mockery v2.22.1. DO NOT EDIT.

package httpscenario

import (
	io "io"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockPostprocessor is an autogenerated mock type for the Postprocessor type
type MockPostprocessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: resp, body
func (_m *MockPostprocessor) Process(resp *http.Response, body io.Reader) (map[string]interface{}, error) {
	ret := _m.Called(resp, body)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Response, io.Reader) (map[string]interface{}, error)); ok {
		return rf(resp, body)
	}
	if rf, ok := ret.Get(0).(func(*http.Response, io.Reader) map[string]interface{}); ok {
		r0 = rf(resp, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Response, io.Reader) error); ok {
		r1 = rf(resp, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockPostprocessor interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPostprocessor creates a new instance of MockPostprocessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPostprocessor(t mockConstructorTestingTNewMockPostprocessor) *MockPostprocessor {
	mock := &MockPostprocessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
