// Code generated by mockery v1.0.0
package coremock

import (
	"context"

	"github.com/yandex/pandora/core"
	"github.com/stretchr/testify/mock"
)

// Aggregator is an autogenerated mock type for the Aggregator type
type Aggregator struct {
	mock.Mock
}

// Report provides a mock function with given fields: s
func (_m *Aggregator) Report(s core.Sample) {
	_m.Called(s)
}

// Run provides a mock function with given fields: ctx, deps
func (_m *Aggregator) Run(ctx context.Context, deps core.AggregatorDeps) error {
	ret := _m.Called(ctx, deps)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.AggregatorDeps) error); ok {
		r0 = rf(ctx, deps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
