// Code generated by mockery v2.20.2. DO NOT EDIT.

package coremock

import mock "github.com/stretchr/testify/mock"

// BorrowedSample is an autogenerated mock type for the BorrowedSample type
type BorrowedSample struct {
	mock.Mock
}

// Return provides a mock function with given fields:
func (_m *BorrowedSample) Return() {
	_m.Called()
}

type mockConstructorTestingTNewBorrowedSample interface {
	mock.TestingT
	Cleanup(func())
}

// NewBorrowedSample creates a new instance of BorrowedSample. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBorrowedSample(t mockConstructorTestingTNewBorrowedSample) *BorrowedSample {
	mock := &BorrowedSample{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
