// Code generated by mockery v1.0.0
package coremock

import mock "github.com/stretchr/testify/mock"

// BorrowedSample is an autogenerated mock type for the BorrowedSample type
type BorrowedSample struct {
	mock.Mock
}

// Return provides a mock function with given fields:
func (_m *BorrowedSample) Return() {
	_m.Called()
}
