// Code generated by mockery v1.0.0
package coremock

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// DataSink is an autogenerated mock type for the DataSink type
type DataSink struct {
	mock.Mock
}

// OpenSink provides a mock function with given fields:
func (_m *DataSink) OpenSink() (io.WriteCloser, error) {
	ret := _m.Called()

	var r0 io.WriteCloser
	if rf, ok := ret.Get(0).(func() io.WriteCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
