// Code generated by mockery v1.0.0
package coremock

import context "context"
import core "github.com/yandex/pandora/core"
import mock "github.com/stretchr/testify/mock"

// Gun is an autogenerated mock type for the Gun type
type Gun struct {
	mock.Mock
}

// Bind provides a mock function with given fields: _a0
func (_m *Gun) Bind(_a0 core.Aggregator) {
	_m.Called(_a0)
}

// Shoot provides a mock function with given fields: _a0, _a1
func (_m *Gun) Shoot(_a0 context.Context, _a1 core.Ammo) {
	_m.Called(_a0, _a1)
}
