// Code generated by mockery v1.0.0
package coremock

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Schedule is an autogenerated mock type for the Schedule type
type Schedule struct {
	mock.Mock
}

// Left provides a mock function with given fields:
func (_m *Schedule) Left() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *Schedule) Next() (time.Time, bool) {
	ret := _m.Called()

	if len(ret) == 1 {
		if rf, ok := ret.Get(0).(func() (time.Time, bool)); ok {
			return rf()
		}
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Start provides a mock function with given fields: startAt
func (_m *Schedule) Start(startAt time.Time) {
	_m.Called(startAt)
}
